### ISSUE TITLE
Raise exception for reserved words (namely `flash`)

### ISSUE THREAD

**Issue by cllns** [hanami/controller#158]
This issue started as a request for documentation that `flash` is a reserved word when using `Hanami::Action::Session`: https://github.com/hanami/hanami/issues/595

Instead of just documenting it, we should help the developer by raising an exception when they try to use any reserved word.

One reserved word is `flash` but we should make sure all reserved words are covered.

(Thanks for the original issue @rafaels88)

**Comment by vladimirich** [comment]
If nobody minds, I'll get this issue. But I have no idea how to implement it yet, hah

**Comment by jodosha** [comment]
@vladimirich Please do.

**Comment by akhramov** [comment]
@vladimirich are you still up for it?

**Comment by akhramov** [comment]
Hi everyone. I think we can go with guard module. The idea behind is dead simple:

* Create a module implementing `#expose` method, which raises an exception if given list of words contains one or more reserved word. Otherwise it calls super.
* Prepend this module to an action.
* Introduce an alias method for `#expose` (`#expose!` or `#_expose`) for internal usage. This alias won't be watched by the guard so no exceptions are raised.

I have created a proof of concept can be found [here](https://github.com/hanami/controller/compare/master...akhramov:feature/158-raise-exception-for-reserved-words).

Any thoughts?

Thank you.

**Comment by vladimirich** [comment]
@jodosha , yep, sorry, was on vacation and forget to inform you

**Comment by vladimirich** [comment]
@akhramov , but if you already did something you can take this issue. What do you think?

**Comment by akhramov** [comment]
@vladimirich let us try, thanks.
