### ISSUE TITLE
Tempfile possibly being stringified during param whitelisting

### ISSUE THREAD

**Issue by matthewling** [hanami/controller#166]
Hallo,

Congratulations on the new release!

While upgrading to 0.8 a file upload feature started to break. On looking more closely, it seemed that when a multi part file upload is made from a form and then checked with a dry-v validation, the value of of a file parameter is stringified.

https://github.com/hanami/controller/blob/master/lib/hanami/action/params.rb#L129

This is the example we have been trying out:

https://github.com/hanami/controller#validations--coercions

I created a little app to see what kind of types were being delivered in the params with and without validations. It seems without validations the tempfile is not being modified.

https://github.com/matthewling/test-file-upload-hanami

Thanks for your help!

Matthew

**Comment by fidothe** [comment]
cc @solnic, after a discussion in dry-v gitter.

**Comment by jodosha** [comment]
@matthewling I'm sorry about this problem that I introduced. I'm closing this ticket because we merged https://github.com/hanami/controller/pull/172 which removes the useless params _stringification_.

We're planning to do a patch release of `hanami-controller` with minor fixes merged during this week.

**Comment by matthewling** [comment]
@jodosha Great stuff! Not a worry at all ... thank you!
