### ISSUE TITLE
[Discussion] Is `session` supposed to return an indifferent hash?

### ISSUE THREAD

**Issue by joneslee85** [hanami/controller#185]
My colleague @createdbypete's just pointed out for me there is a regression with the accessor `action.session` when he upgraded our internal app to Hanami 0.9

Before:

```
action.session[:key] #=> the value
```

Now:

```
action.session[:key] #=> nil
```

I could not find any traces in the session code that cast to `Utils::Hash` so I assume that it is with intention `session` would return a original hash or whatever that `env` returns.

Now let's take a moment to discuss if `session` should be casted to `Utils::Hash` OR respect whatever rack returns. There is already a similar pattern with `params` in which we cast and for the `raw.params` we leave it intact. 

Thoughts? cc @hanami/core-team @createdbypete

**Comment by jodosha** [comment]
@joneslee85 @createdbypete I'm sorry about this confusion.

First of all, _indifferent access_ shouldn't be considered anymore. We removed support for it in the latest versions.

We should make session values to be accessible only with symbols. This is for consistency sake with the other parts of Hanami (action params, entities attributes etc..).

We should avoid to assign `Utils::Hash` instances to `env['rack.session']` because this can create problems with the surrounding ecosystem and with Rack itself.

If necessary, we can wrap `env['rack.session']` with a brand new `Hanami::Action::Sessions::Session` object that:

  1. respond to `#[]` and `#[]=`
  2. accepts only symbols
  3. writes the proper value into Rack env (string keys?).

WDYT?

---

PS: @joneslee85 When you have a second, please check Gitter.

**Comment by joneslee85** [comment]
@jodosha thanks for the clarification

I am with you on avoiding `Utils::Hash` and thus I don't think it is necessary to wrap `env['rack.session']`.

@createdbypete please change the key to string

**Comment by createdbypete** [comment]
@jodosha +1 to the consistency using symbols if possible. Would be in line with the existing docs and guides examples. 

What's frustrating is this appears to only be an issue in the unit tests where a raw `Hash` is passed to the action. The case of converting the key to a string is handled by the Rack [`SessionHash`](https://github.com/rack/rack/blob/1-6-stable/lib/rack/session/abstract/id.rb#L61) in any other case when Rack middleware is involved so anything put in as a wrapper should probably have a similar interface?
